trigger:
- main
  
variables:
  azureSubscription: 'Demo Account'
  region: 'eastus'

stages:
- template: azure-release-pipelines-stage-template.yml
  parameters:
    stageName: 'CI'
    environment: 'API'
    azureSubscription: ${{ variables.azureSubscription }}
    resourceGroupName: 'rutzsco-demo-logic-app'
    region: ${{ variables.region }}
    logicAppName: 'rutzsco-demo-logic-app'
    logicAppStorageName: 'rutzscodla'
    templateFile: 'Infrastructure/main.bicep'

