trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'workflows-build-ci'
    trigger:
      branches:
        - main

variables:
  azureSubscription: 'Terraform'
  azureSubscriptionId: 'b79b3641-f295-4473-b807-e858d16b195b'
  region: 'centralus'

stages:
- template: cd-stage-template.yml
  parameters:
    stageName: 'CI'
    environment: 'LA-CI'
    azureSubscription: $(azureSubscription)
    azureSubscriptionId: $(azureSubscriptionId)
    resourceGroupName: 'jmas-demo-logic-app-ci'
    region: $(region)
    logicAppName: 'jmas-demo-logic-app-ci'
    storageAccountName: 'jmdemolablobsci'
    triggerFrequency: 'Minute'
- template: cd-stage-template.yml
  parameters:
    stageName: 'QA'
    environment: 'LA-QA'
    azureSubscription: $(azureSubscription)
    azureSubscriptionId: $(azureSubscriptionId)
    resourceGroupName: 'rutzsco-demo-logic-app-qa'
    region: $(region)
    logicAppName: 'rutzsco-demo-logic-app-qa'
    storageAccountName: 'rutzscodemolablobsqa'
    triggerFrequency: 'Day'