trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'workflows-build-ci'
    trigger:
      branches:
        - local-func

variables:
  azureSubscription: 'Terraform'
  azureSubscriptionId: 'b79b3641-f295-4473-b807-e858d16b195b'
  region: 'centralus'

stages:
- template: cd-stage-template.yml
  parameters:
    stageName: 'CI'
    environment: 'LA-CI'
    azureSubscription: $(azureSubscription)
    azureSubscriptionId: $(azureSubscriptionId)
    resourceGroupName: 'demo-logic-apps-std-dev'
    region: $(region)
    logicAppName: 'c4z3pife3f436-logic-app-ci'
- template: cd-stage-template.yml
  parameters:
    stageName: 'QA'
    environment: 'LA-QA'
    azureSubscription: $(azureSubscription)
    azureSubscriptionId: $(azureSubscriptionId)
    resourceGroupName: 'demo-logic-apps-std-qa'
    region: 'eastus2' #$(region)
    logicAppName: '3rt7ivk3m2zwk-logic-app-qa'