trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'Workflows - Build'

variables:
  azureSubscription: 'Demo Account'
  region: 'eastus'
  logicAppName: 'logic-rutzsco-demo-logic-app-ci'

stages:
- stage: CI
  displayName: 'CI'
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    environment: LA-CI
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@1
            displayName: 'Deploy logic app workflows'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'functionApp'
              appName: '$(logicAppName)'
              package: '$(Pipeline.Workspace)/build/App/LA.zip'
              deploymentMethod: 'zipDeploy'
