parameters: 
- name: stageName
  default: ''
- name: environment
  default: ''
- name: azureSubscription
  default: ''
- name: azureSubscriptionId
  default: ''
- name: resourceGroupName
  default: ''
- name: region
  default: ''
- name: logicAppName
  default: ''

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageName }}

    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: ${{ parameters.environment }}
      pool:
        vmImage: 'ubuntu-latest'
  
      strategy:
        runOnce:
          deploy:
  
            steps:
            - task: AzureFunctionApp@1
              displayName: 'Deploy logic app workflows'
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                appType: 'functionApp'
                appName: ${{ parameters.logicAppName }}
                package: '$(Pipeline.Workspace)/build/App/LA.zip'
                deploymentMethod: 'zipDeploy'
                AppSettings: '-WORKFLOWS_SUBSCRIPTION_ID ${{ parameters.azureSubscriptionId }} -WORKFLOWS_LOCATION_NAME ${{ parameters.region }} -WORKFLOWS_RESOURCE_GROUP_NAME ${{ parameters.resourceGroupName }}'