trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'infra-build-ci'
    trigger:
      branches:
        - jm-workflows

variables:
  azureServiceConnection: 'Terraform'
  region: 'centralus'
  templateFile: '$(Pipeline.Workspace)/build/Infrastructure/main.bicep'

pool:
  vmImage: 'ubuntu-latest'

stages:
- template: azure-release-stage-template.yml
  parameters:
    stageName: 'CI'
    environment: 'LA-CI'
    azureSubscription: $(azureSubscription)
    resourceGroupName: 'demo-logic-apps-std-dev'
    region: $(region)
    templateFile: $(templateFile)
- template: azure-release-stage-template.yml
  parameters:
    stageName: 'QA'
    environment: 'LA-QA'
    azureSubscription: $(azureSubscription)
    resourceGroupName: 'demo-logic-apps-std-qa'
    region: $(region)
    templateFile: $(templateFile)