trigger:
- main
  
variables:
  azureServiceConnection: 'Demo Account'
  region: 'eastus'
  logicAppStorageName: 'rutzscodemola'
  templateFile: '$(Build.SourcesDirectory)/Infrastructure/main.bicep'

pool:
  vmImage: 'ubuntu-latest'

stages:
- template: azure-release-stage-template.yml
  parameters:
    stageName: 'CI'
    environment: 'LA-CI'
    azureSubscription: $(azureSubscription)
    resourceGroupName: 'rutzsco-demo-logic-app-ci'
    region: $(region)
    logicAppName: 'rutzsco-demo-logic-app-ci'
    logicAppStorageName: $(logicAppStorageName)
    templateFile: $(templateFile)
- template: azure-release-stage-template.yml
  parameters:
    stageName: 'QA'
    environment: 'LA-QA'
    azureSubscription: $(azureSubscription)
    resourceGroupName: 'rutzsco-demo-logic-app-qa'
    region: $(region)
    logicAppName: 'rutzsco-demo-logic-app-qa'
    logicAppStorageName: $(logicAppStorageName)
    templateFile: $(templateFile)