trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'Infra - Build'

variables:
  azureServiceConnection: 'Terraform'
  region: 'centralus'
  resourceGroupName: 'demo-logic-apps-standard-devops'
  logicAppName: 'demo-logic-apps-standard-devops'
  logicAppStorageName: 'jmdemolastr'
  templateFile: 'Infrastructure/main.bicep'

pool:
  vmImage: 'ubuntu-latest'

stages:
- template: azure-release-stage-template.yml
  parameters:
    stageName: 'CI'
    environment: 'LA-CI'
    azureSubscription: $(azureSubscription)
    resourceGroupName: 'rutzsco-demo-logic-app-ci'
    region: $(region)
    logicAppName: $(logicAppName)
    logicAppStorageName: $(logicAppStorageName)
    templateFile: $(templateFile)
- template: azure-release-stage-template.yml
  parameters:
    stageName: 'QA'
    environment: 'LA-QA'
    azureSubscription: $(azureSubscription)
    resourceGroupName: 'rutzsco-demo-logic-app-qa'
    region: $(region)
    logicAppName: $(logicAppName)
    logicAppStorageName: $(logicAppStorageName)
    templateFile: $(templateFile)